// Self-contained mobile approval page. No LINE text is injected as HTML.
export const assistantHtml = [
  '<!doctype html><html lang="ja"><head><meta charset="utf-8">',
  '<meta name="viewport" content="width=device-width,initial-scale=1">',
  '<title>Prospect｜Aチーム AI秘書</title>',
  '<style>',
  ':root{font-family:system-ui,-apple-system,sans-serif;color:#13243b;background:#f4f7fa}',
  'body{margin:0;padding:0 12px 50px}main{max-width:900px;margin:auto}',
  'header{padding:21px 4px 12px}h1{font-size:23px;margin:0 0 7px}',
  'p{margin:5px 0;color:#5c6a7b;font-size:13px}',
  '.panel,.item{border:1px solid #dbe3eb;background:#fff;border-radius:13px;padding:15px;margin:12px 0}',
  '.row{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}',
  '.stack{display:flex;flex-direction:column;gap:7px}label{font-size:14px;font-weight:650}',
  'input,textarea{box-sizing:border-box;width:100%;border:1px solid #b9c8d7;border-radius:9px;padding:11px;font:inherit}',
  'textarea{min-height:110px;line-height:1.6;resize:vertical}',
  'button{cursor:pointer;background:#195dcb;color:#fff;border:0;border-radius:9px;padding:10px 16px;font-weight:650}',
  'button.secondary{background:#edf2f7;color:#203149}button.danger{background:#fff3ef;color:#a53322}',
  'button:disabled{opacity:.5;cursor:not-allowed}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #9bbffd}',
  '.small{font-size:12px;color:#718093}.body{white-space:pre-wrap;line-height:1.6;margin:12px 0}',
  '.status{padding:4px 8px;border-radius:12px;background:#f0f4f9;font-size:12px}',
  '.note{padding:10px;border-radius:8px;background:#fff8e7;color:#724b03;font-size:12px;margin:7px 0}',
  '.hide{display:none}',
  '</style></head><body><main>',
  '<header><h1>Prospect｜Aチーム AI秘書</h1>',
  '<p>LINE公式アカウントの受信と返信案。実際の送信は承認ボタンを押した時だけです。</p></header>',
  '<section id="login" class="panel stack"><label for="token">管理者アクセストークン</label>',
  '<input id="token" type="password" autocomplete="off" placeholder="管理者用トークンを入力">',
  '<div class="row"><span class="small">トークンはブラウザに保存しません</span><button id="unlock">受信箱を開く</button></div></section>',
  '<section id="inbox" class="hide"><div class="panel row"><strong id="summary">受信確認中</strong>',
  '<button id="refresh" class="secondary">最新に更新</button></div><div id="alerts" role="status"></div>',
  '<div id="messages"></div></section>',
  '</main><script src="/assistant/app.js" defer></script></body></html>'
].join('');

export const assistantClientJs = [
  '(function(){',
  '"use strict";',
  'var token="";',
  'var $=function(id){return document.getElementById(id)};',
  'var box=$("messages"),alerts=$("alerts");',
  'var statusLabels={new:"下書き待ち",drafting:"GPT作成中",draft_failed:"生成エラー",draft_ready:"承認待ち",manual:"画像等・手動確認",sending:"送信処理中",sent:"送信済み",send_unknown:"送信成否未確定",ignored:"対応不要"};',
  'var routeLabels={"a/saitama-shibakawa":"さいたま芝川","a/sugishita":"杉下","a/mizuhodai":"みずほ台","a/kamekubo":"亀久保","a/ageo-fujimi":"上尾富士見","a/ageo-shibakawa":"上尾芝川","a/kasumigaseki-nishi":"霞ヶ関西"};',
  'function element(tag,text,cls){var e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}',
  'function notice(message){alerts.replaceChildren(element("div",message,"note"));}',
  'async function api(path,data){var r=await fetch("/assistant/api/"+path,{method:data?"POST":"GET",headers:{"authorization":"Bearer "+token,"content-type":"application/json"},body:data?JSON.stringify(data):undefined,cache:"no-store"});var d=await r.json();if(!r.ok||d.ok===false)throw Error(d.code||"request_failed");return d;}',
  'async function reload(){',
  '  try{var data=await api("messages");$("summary").textContent="未対応 "+data.countActive+" 件";box.replaceChildren();',
  '    if(!data.messages.length)box.append(element("div","受信メッセージはありません。","panel"));',
  '    data.messages.forEach(function(m){box.appendChild(card(m));});',
  '    alerts.replaceChildren();',
  '  }catch(e){notice("取得に失敗しました: "+e.message);}}',
  'function card(m){',
  '  var c=element("article",undefined,"item");var head=element("div",undefined,"row");',
  '  var venue=element("strong",routeLabels[m.route]||m.route);',
  '  var when=new Date(m.received_at).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"});',
  '  var meta=element("span",when+" / "+(statusLabels[m.status]||m.status),"small");head.append(venue,meta);c.append(head);',
  '  c.append(element("p","ユーザーID末尾: "+m.user_id.slice(-6)+"　種別: "+m.kind,"small"));',
  '  c.append(element("div",m.kind==="text"?m.body:"テキスト以外のメッセージです。LINE公式管理画面で確認してください。","body"));',
  '  if(m.error)c.append(element("div",m.error,"note"));',
  '  if(m.status==="send_unknown")c.append(element("div","二重送信防止のため、この画面から再送できません。LINE公式管理画面を確認してください。","note"));',
  '  if(m.status==="draft_ready"){',
  '    c.append(element("label","GPTの返信案（編集可）"));',
  '    var area=element("textarea");area.value=m.draft||"";area.maxLength=2000;c.append(area);',
  '    var buttons=element("div",undefined,"row");',
  '    var send=element("button","確認してLINEに送信");',
  '    send.addEventListener("click",async function(){if(!area.value.trim())return notice("返信文を入力してください");',
  '      if(!confirm("この文面を実際のLINEに送信します。よろしいですか？"))return;',
  '      send.disabled=true;try{await api("send",{id:m.id,text:area.value});await reload();}catch(e){notice("送信状態を確認してください: "+e.message);send.disabled=true;}});',
  '    buttons.append(send);c.append(buttons);',
  '  }',
  '  if(m.status==="draft_failed"||m.status==="draft_ready"){var retry=element("button","下書き再生成","secondary");',
  '    retry.addEventListener("click",async function(){retry.disabled=true;try{await api("redraft",{id:m.id});await reload();}catch(e){notice("再生成できません: "+e.message);retry.disabled=false;}});c.append(retry);}',
  '  if(!["sent","ignored","sending","send_unknown"].includes(m.status)){var skip=element("button","返信不要として完了","danger");',
  '    skip.addEventListener("click",async function(){if(!confirm("返信不要として記録しますか？"))return;skip.disabled=true;try{await api("dismiss",{id:m.id});await reload();}catch(e){notice(e.message);skip.disabled=false;}});c.append(skip);}',
  '  return c;',
  '}',
  '$("unlock").addEventListener("click",async function(){token=$("token").value.trim();if(!token)return;',
  '  $("token").value="";$("login").classList.add("hide");$("inbox").classList.remove("hide");await reload();});',
  '$("refresh").addEventListener("click",reload);',
  '})();'
].join('\n');
